# Generated by Django 3.0.5 on 2020-04-12 06:32

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('heading_min', models.TextField(max_length=200, verbose_name='Минимальное описание (100 сим)')),
                ('heading_max', models.TextField(max_length=20000, verbose_name='Полное описание услуги')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('variant_2', models.BooleanField(default=True, verbose_name='Опубликовать вариантом картинки?')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='all_services/img/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название операции')),
                ('title', models.TextField(max_length=20000, verbose_name='Описание операции')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена операции')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='services_single/img/%Y/%m/%d/', verbose_name='Картинка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_services.AllServices', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
