# Generated by Django 3.0.5 on 2020-04-04 10:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservices',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='all_services/img/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
