# Generated by Django 3.0.5 on 2020-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0003_auto_20200404_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservices',
            name='heading_max',
            field=models.TextField(max_length=2000, verbose_name='Полное описание услуги'),
        ),
    ]
