# Generated by Django 3.0.5 on 2020-04-05 02:42

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0004_auto_20200404_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservices',
            name='img_icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='all_services/img/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='allservices',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
        migrations.AddField(
            model_name='allservices',
            name='variant_1',
            field=models.BooleanField(default=True, verbose_name='Опубликовать вариантом иконк?'),
        ),
        migrations.AddField(
            model_name='allservices',
            name='variant_2',
            field=models.BooleanField(default=True, verbose_name='Опубликовать вариантом картин?'),
        ),
    ]
