# Generated by Django 3.0.5 on 2020-04-05 02:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0005_auto_20200405_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservices',
            name='img_icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='all_services/img_icon/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
