# Generated by Django 3.0.5 on 2020-04-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0006_auto_20200405_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allservices',
            name='img_icon',
        ),
    ]
