# Generated by Django 3.0.5 on 2020-04-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0007_remove_allservices_img_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allservices',
            name='variant_1',
        ),
    ]
