# Generated by Django 3.0.5 on 2020-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0008_remove_allservices_variant_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservices',
            name='variant_2',
            field=models.BooleanField(default=True, verbose_name='Опубликовать вариантом картинки?'),
        ),
    ]
