# Generated by Django 3.0.5 on 2020-04-08 08:44

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('all_services', '0009_auto_20200406_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allservices',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.CreateModel(
            name='ServiceSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название операции')),
                ('title', models.TextField(max_length=2000, verbose_name='Описание операции')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='services_single/img/%Y/%m/%d/', verbose_name='Картинка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_services.AllServices', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
