# Generated by Django 3.0.5 on 2020-04-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
