# Generated by Django 3.0.5 on 2020-04-12 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200, verbose_name='Сообщение')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('desired_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Желаемая дата')),
                ('car', models.CharField(max_length=100, verbose_name='Автобомиль')),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Год авто')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_services.AllServices', verbose_name='Желаемый сервис')),
            ],
            options={
                'verbose_name': 'Запись на ремонт',
                'verbose_name_plural': 'Записи на ремонт',
            },
        ),
    ]
