# Generated by Django 3.0.5 on 2020-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('home', models.CharField(max_length=5, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Место расположения',
                'verbose_name_plural': 'Место расположения',
            },
        ),
        migrations.CreateModel(
            name='SocialContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, verbose_name='Время работы')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Mail')),
                ('vk', models.CharField(blank=True, max_length=200, null=True, verbose_name='VK')),
                ('ok', models.CharField(blank=True, max_length=200, null=True, verbose_name='OK')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
