# Generated by Django 3.0.5 on 2020-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, verbose_name='Время работы')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=100, verbose_name='Mail')),
                ('vk', models.CharField(max_length=200, verbose_name='VK')),
                ('ok', models.CharField(max_length=200, verbose_name='OK')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
