# Generated by Django 3.0.5 on 2020-04-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_address', '0002_socialcontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcontacts',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='socialcontacts',
            name='ok',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='OK'),
        ),
        migrations.AlterField(
            model_name='socialcontacts',
            name='vk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VK'),
        ),
    ]
